@url_dev = http://localhost:3055/v1/api


### product
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: e184957d377fd62f28acd22efbc74b21cb2e51700b6f78c84ca61e8eee5dc5c5aa6864302bab6030b60a5f00db6b05e8d6684e30b6650848c231d21ba3e780b9
x-client-id: 65f12bdb7ed581a7111c6ef1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWYxMmJkYjdlZDU4MWE3MTExYzZlZjEiLCJlbWFpbCI6InRxcGh1QGdtYWlsLmNvbSIsImlhdCI6MTcxMDQ3NjM0NiwiZXhwIjoxNzEwNjQ5MTQ2fQ.DpO_ivSIpZw8xNCq8sRkG3rnAbcsl3D5QXP2sr68_NQ

{
    "product_name": "Macbook",
    "product_description": "High-quality",
    "product_price": 5000,
    "product_type": "Electronic",
    "product_thumb": "product_thumb",
    "product_quantity": 5,
    "product_attributes": {
        "manufacturer": "Apple",
        "model": "Apple",
        "color": "Black"
    }
}
